#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5
hfloat=$(expr $h*0.9 | bc)
hint=${hfloat/.*}
CACHE="$HOME/.cache/tmpimg"

if [[ "$( file -Lb --mime-type "$file")" =~ ^image && $lf_preview == true ]]; then
  kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x3" "$file" < /dev/null > /dev/tty
  exit 1
fi

if [[ "$( file -Lb --mime-type "$file")" =~ ^application/pdf && $lf_preview == true ]]; then
  pdftoppm -jpeg -f 1 -singlefile "$file" "$CACHE"
  kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x$hint@${x}x3" "${CACHE}.jpg" < /dev/null > /dev/tty
  exit 1
fi

cat "$file"
