[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.iosevka-custom.variants.design]
l = "serifed-semi-tailed"
zero = "dotted"
one = "base"
three = "flat-top"
at = "compact"
lig-ltgteq = "slanted"

[buildPlans.iosevka-custom.variants.italic]
zero = "dotted"
three = "flat-top"

[buildPlans.iosevka-custom.ligations]
inherits = "dlig"
enables = ["exeqeq", "eqeqeq", "llggeq"]
