# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig(False)

# Restore open sites when qutebrowser is reopen
c.auto_save.session = True

# Default font size
c.fonts.default_size = "12pt"

# Font used for the hints
c.fonts.hints = "bold 13pt default_family"

# Enable smooth scrolling for web pages. Note smooth scrolling does not
# work with the `:scroll-px` command.
# Type: Bool
c.scrolling.smooth = False

# Dark mode
# c.colors.webpage.darkmode.enabled = True

# Padding (in pixels) around text for tabs.
# Type: Padding
c.tabs.padding = {'bottom': 5, 'left': 5, 'right': 5, 'top': 5}

# Page to open if :open -t/-b/-w is used without URL. Use `about:blank`
# for a blank page.
# Type: FuzzyUrl
c.url.default_page = 'https://www.google.com/'

# Page(s) to open at the start.
# Type: List of FuzzyUrl, or FuzzyUrl
c.url.default_page = 'https://www.google.com/'

# Search engines
c.url.searchengines = {
    'DEFAULT': 'https://duckduckgo.com/?q={}',
    'dd': 'https://duckduckgo.com/?q={}',
    'gg': 'https://www.google.com/search?q={}',
    'am': 'https://www.amazon.com/s?k={}',
    're': 'https://www.reddit.com/r/{}',
    'ub': 'https://www.urbandictionary.com/define.php?term={}',
    'wiki': 'https://en.wikipedia.org/wiki/{}',
    'yt': 'https://www.youtube.com/results?search_query={}'
}

# Hide the window decoration.  This setting requires a restart on
# Wayland.
# Type: Bool
# c.window.hide_decoration = True

# Text color of the completion widget. May be a single color to use for
# all columns or a list of three colors, one for each column.
# Type: List of QtColor, or QtColor
c.colors.completion.fg = '#d5c4a1'

# Background color of the completion widget for odd rows.
# Type: QssColor
c.colors.completion.odd.bg = '#333333'

# Background color of the completion widget for even rows.
# Type: QssColor
c.colors.completion.even.bg = '#202020'

# Background color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.bg = '#C59EF5'

# Top border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.item.selected.border.top = '#151515'

# Bottom border color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.border.bottom = '#151515'

# Foreground color of the matched text in the completion.
# Type: QssColor
c.colors.completion.match.fg = '#d75f5f'

# Background color for the download bar.
# Type: QssColor
c.colors.downloads.bar.bg = '#202020'

# Foreground color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.fg = '#d5c4a1'

# Background color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.bg = '#202020'

# Foreground color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.fg = '#d4c5a1'

# Background color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.bg = '#202020'

# Default foreground color of the URL in the statusbar.
# Type: QssColor
c.colors.statusbar.url.fg = '#C59EF5'
c.colors.statusbar.url.hover.fg = '#C59EF5'

# Foreground color of the URL in the statusbar on error.
# Type: QssColor
c.colors.statusbar.url.error.fg = '#d75f5f'

# Foreground color of the URL in the statusbar on successful load
# (http).
# Type: QssColor
c.colors.statusbar.url.success.http.fg = '#84edb9'

# Foreground color of the URL in the statusbar on successful load
# (https).
# Type: QssColor
c.colors.statusbar.url.success.https.fg = '#C59EF5'

# Foreground color of the URL in the statusbar when there's a warning.
# Type: QssColor
c.colors.statusbar.url.warn.fg = '#cd950c'

# Background color of the tab bar.
# Type: QtColor
c.colors.tabs.bar.bg = '#202020'

# Foreground color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.fg = '#707070'

# Background color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.bg = '#202020'

# Foreground color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.fg = '#707070'

# Background color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.bg = '#202020'

# Foreground color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.fg = '#363A4F'

# Background color of selected odd tabs.
# Type: QtColor
# c.colors.tabs.selected.odd.bg = '#202020'
# c.colors.tabs.selected.odd.bg = '#35363A'
c.colors.tabs.selected.odd.bg = '#C59EF5'

# Foreground color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.fg = '#363A4F'

# Background color of selected even tabs.
# Type: QtColor
# c.colors.tabs.selected.even.bg = '#202020'
# c.colors.tabs.selected.even.bg = '#35363A'
c.colors.tabs.selected.even.bg = '#C59EF5'

# Background color for pinned tabs
c.colors.tabs.pinned.selected.even.bg = '#b32b2b'
c.colors.tabs.pinned.selected.odd.bg = '#b32b2b'

# Bindings for normal mode
config.bind(
    ';M', 'hint --rapid links spawn open -na /Applications/mpv.app {hint-url}')
config.bind('<Meta+n>', 'open -p')
config.bind('<Meta+w>', 'close')
config.bind('<Meta+[>', 'back')
config.bind('<Meta+]>', 'forward')
config.bind('<Ctrl+Space>', 'set-cmd-text -s :tab-select')
config.bind('M', 'hint links spawn open -na /Applications/mpv.app {hint-url}')
config.bind('m', 'spawn open -na /Applications/mpv.app {url}')
config.bind('<Ctrl+q>', 'tab-focus last')
config.bind('<Ctrl+q>', 'tab-focus last', mode='insert')
config.bind('<Ctrl+q>', 'tab-focus last', mode='passthrough')
config.bind('<<', 'tab-move -')
config.bind('>>', 'tab-move +')
config.bind('cv', 'download-open')
config.bind('<Ctrl+Shift+q>', 'quickmark-save')
config.bind('<Ctrl+Shift+b>', 'bookmark-add')

# CSS/themes bindings
config.bind(
    ',my', 'config-cycle content.user_stylesheets "~/Dropbox/solarized-everything-css/my_custom.css" ""')
config.bind(',md', 'config-cycle content.user_stylesheets "~/Dropbox/solarized-everything-css/my_custom-dark.css" ""')
config.bind(',df', 'config-cycle content.user_stylesheets "~/Dropbox/solarized-everything-css/apprentice-all-sites.css" ""')
config.bind(',ap', 'config-cycle content.user_stylesheets ~/Dropbox/solarized-everything-css/apprentice-all-sites.css ""')
config.bind(',gr', 'config-cycle content.user_stylesheets ~/Dropbox/solarized-everything-css/gruvbox-all-sites.css ""')
config.bind(',so', 'config-cycle content.user_stylesheets ~/Dropbox/solarized-everything-css/solarized-dark-all-sites.css ""')
