#!/usr/bin/env sh

export VISUAL=nvim
export EDITOR="$VISUAL"

# notesDir="$HOME/Sync/Notes-zk"
notesDir="$HOME/Sync/Notes-Database"
# notesDir="$HOME/pCloud/Notes-Flow"

# noteFilename="$HOME/Dropbox/Notes-Database/Daily-Notes/$(date +%Y-%m-%d).md"
noteFilename="$notesDir""/Daily-Notes/$(date +%Y-%m-%d).md"
# noteFilename="$notesDir""/journal/daily/$(date +%Y-%m-%d).md"
# term="/usr/local/bin/alacritty --working-directory $HOME/Dropbox/Notes-Database -d 90 20"
# term="/usr/local/bin/alacritty --working-directory $HOME/Dropbox/Notes-Database"

# echo $noteFilename
# process="$term -e $editor $noteFilename"
# process="subl $noteFilename"

# ~/scripts/lof "$process"
# status=$?

# [ $status -eq 1 ] && $process && exit
# $process && exit
# /usr/local/bin/alacritty --working-directory "$notesDir" -o window.dimensions.columns=98 window.dimensions.lines=24 -e /opt/homebrew/bin/fish -ic "$editor $noteFilename" && exit
wezterm-gui --config initial_rows=33 --config initial_cols=132 start --cwd $notesDir $EDITOR $noteFilename
