#!/usr/bin/env bash

boottime=$(sysctl -n kern.boottime | awk '{print $4}' | sed 's/,//g')
unixtime=$(date +%s)
timeAgo=$(($unixtime - $boottime))

days=$(($timeAgo / 86400))
remaining_seconds=$(($timeAgo % 86400))
hours=$(echo "scale=1; $remaining_seconds / 3600" | bc)

if [[ "$days" -eq 0 ]]; then
  result=$(printf "%.1f hours" $hours)
elif [[ "$days" -eq 1 ]]; then
  result=$(printf "1 day, %.1f hours" $hours)
else
  result=$(printf "%d days, %.1f hours" $days $hours)
fi

echo "$result "
