#!/usr/bin/env bash

folder="neovim-stable"
dir="$HOME/other_repos/neovim"
download_location="$HOME/Desktop/Inbox/neovim"
download_dir="$download_location/$folder"

if [ ! -d "$download_dir" ]; then
  echo "$download_dir does not exist. Creating directory..."
  mkdir -p "$download_dir"
fi

trash $download_dir/nvim-macos.tar.gz
curl --output-dir $download_dir -LO https://github.com/neovim/neovim/releases/download/stable/nvim-macos.tar.gz

if [ -e "$download_dir/nvim-macos.tar.gz" ]; then
  tar -xzf $download_dir/nvim-macos.tar.gz --directory $download_dir
  ln -fs $download_dir/nvim-macos/bin/nvim $HOME/bin/
fi

