#!/usr/bin/env bash

current_date=$(date +%Y-%m-%d)
dir="$HOME/other_repos/neovim"
download_location="$HOME/Desktop/Inbox/neovim"
download_dir="$download_location/$current_date"

if [ ! -d "$download_dir" ]; then
  echo "$download_dir does not exist. Creating directory..."
  mkdir -p "$download_dir"
fi

tar_file="nvim-macos-arm64.tar.gz"
dir_path="nvim-macos-arm64"
trash $download_dir/$tar_file
curl --output-dir $download_dir -LO https://github.com/neovim/neovim/releases/download/nightly/$tar_file

if [ -e "$download_dir/$tar_file" ]; then
  if [ ! -d "$dir" ]; then
    echo "$dir does not exist. Creating directory..."
    mkdir -p "$dir"
  fi
  trash $dir/*
  cp -r $download_dir/$tar_file $dir/
  tar xzf $dir/$tar_file --directory $dir

  if [ -x "$dir/$dir_path/bin/nvim" ]; then
    ln -fs $dir/$dir_path/bin/nvim $HOME/bin/
    echo "🆗 nvim binary simlink created in ~/bin directory"
  else
    echo "🚨 Could not simlink nvim binary!"
  fi
fi

