#!/usr/bin/env bash

dir="$HOME/other_repos/neovim"

if [ ! -d "$dir" ]; then
  echo "$dir does not exist. Creating directory..."
  mkdir "$dir"
fi

trash $dir/*
curl --output-dir $dir -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
tar -xzf $dir/nvim-macos.tar.gz --directory $dir

ln -fs $dir/nvim-macos/bin/nvim $HOME/bin/
