#!/usr/bin/env sh

# # No need to load path if using skhd
# export PATH="/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin:/usr/local/bin:$HOME/.fzf/bin:$HOME/bin"

export VISUAL=nvim
export EDITOR="$VISUAL"

term="/usr/local/bin/alacritty --args -o window.dimensions.columns=160 -o window.dimensions.lines=40"
# fm="$HOME/bin/nnn"
fm="$(brew --prefix)/bin/lf"

open -na $term -e $fm -command 'set sortby time; set info time; set reverse' $HOME/Downloads

