#!/usr/bin/env bash
# source: https://github.com/joshmedeski/tmux-nerd-font-window-name

NAME=$1

case $NAME in
    tmux)
        echo ""
        ;;
    fish | zsh | bash)
        # echo ""
        # echo ""
        echo ""
        ;;
    nvim)
        echo ""
        ;;
    vi | vim | lvim)
        echo ""
        ;;
    lazygit | git)
        echo ""
        ;;
    node)
        echo "󰎙"
        ;;
    ruby)
        echo ""
        ;;
    Python)
        echo "󰌠"
        ;;
    go)
        echo ""
        ;;
    lf | lfcd | yazi | joshuto)
        echo ""
        ;;
    *)
        echo "$NAME"
        ;;
esac
