# Alacritty Colors (github_monochrome_blue)

# Default colors
[colors.primary]
background = "#012351"
foreground = "#C8D3F5"

[colors.cursor]
cursor     = "#C8D3F5"
text       = "#012351"

[colors.selection]
background = "#3B5070"
text       = "#C8D3F5"

[colors.normal]
black      = "#2A384B"
red        = "#FF7B72"
green      = "#9ECE6A"
yellow     = "#E7C297"
blue       = "#79C0FF"
magenta    = "#E0B8FD"
cyan       = "#78DCE8"
white      = "#8A92B2"

[colors.bright]
black      = "#3E526F"
red        = "#FF928C"
green      = "#9FE044"
yellow     = "#F4D0A8"
blue       = "#9BCCFF"
magenta    = "#E8CAFF"
cyan       = "#6AEDFC"
white      = "#C8D3F5"

