[colors.primary]
background = "#000000"

[colors.cursor]
text = "#1E1E2E"
cursor = "#D5D5D5"

[colors.normal]
black =   "#000000"
red =     "#afaaaa"
green =   "#505559"
yellow =  "#a7a7a7"
blue =    "#56698a"
magenta = "#d5d5d5"
cyan =    "#99AABB"
white =   "#e5e9f0"


[colors.bright]
black =   "#4c566a"
red =     "#bf616a"
green =   "#a3be8c"
yellow =  "#ebcb8b"
blue =    "#81a1c1"
magenta = "#b48ead"
cyan =    "#8fbcbb"
white =   "#eceff4"
