# one dark
[colors.primary]
# background = '0x1E222A'
background = '0x002635' # wind theme
foreground = '0xabb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

[colors.cursor]
# cursor = "#74ADE8"
# cursor = "#F08E48"
cursor = "#F34B00"
text = "#282C34"

[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# tokyo_night_moon
# [colors.primary]
# background = "0x222436"
# foreground = "0xc8d3f5"
#
# [[colors.indexed_colors]]
# color = "0xff966c"
# index = 16
#
# [[colors.indexed_colors]]
# color = "0xc53b53"
# index = 17
#
# [colors.bright]
# black = "0x444a73"
# blue = "0x82aaff"
# cyan = "0x86e1fc"
# green = "0xc3e88d"
# magenta = "0xc099ff"
# red = "0xff757f"
# white = "0xc8d3f5"
# yellow = "0xffc777"
#
# [colors.cursor]
# cursor = "#C8D3F5"
# text = "0x222436"
#
# [colors.normal]
# black = "0x1b1d2b"
# blue = "0x82aaff"
# cyan = "0x86e1fc"
# green = "0xc3e88d"
# magenta = "0xc099ff"
# red = "0xff757f"
# white = "0x828bb8"
# yellow = "0xffc777"
#
# [colors.primary]
# background = "0x222436"
# foreground = "0xc8d3f5"

# [schemes]
# draw_bold_text_with_bright_colors = true
#
# [schemes.duskfox.bright]
# black = "0x47407d"
# blue = "0x65b1cd"
# cyan = "0xa6dae3"
# green = "0xb1d196"
# magenta = "0xccb1ed"
# red = "0xf083a2"
# white = "0xe2e0f7"
# yellow = "0xf9cb8c"
#
# [schemes.duskfox.cursor]
# cursor = "0xe0def4"
# text = "0x232136"
#
# [schemes.duskfox.normal]
# black = "0x393552"
# blue = "0x569fba"
# cyan = "0x9ccfd8"
# green = "0xa3be8c"
# magenta = "0xc4a7e7"
# red = "0xeb6f92"
# white = "0xe0def4"
# yellow = "0xf6c177"
#
# [schemes.duskfox.primary]
# background = "0x232136"
# foreground = "0xe0def4"
#
# [[schemes.frappe.indexed_colors]]
# color = "#EF9F76"
# index = 16
#
# [[schemes.frappe.indexed_colors]]
# color = "#F2D5CF"
# index = 17
#
# [schemes.frappe.bright]
# black = "#626880"
# blue = "#8CAAEE"
# cyan = "#81C8BE"
# green = "#A6D189"
# magenta = "#F4B8E4"
# red = "#E78284"
# white = "#A5ADCE"
# yellow = "#E5C890"
#
# [schemes.frappe.cursor]
# cursor = "#F2D5CF"
# text = "#303446"
#
# [schemes.frappe.dim]
# black = "#51576D"
# blue = "#8CAAEE"
# cyan = "#81C8BE"
# green = "#A6D189"
# magenta = "#F4B8E4"
# red = "#E78284"
# white = "#B5BFE2"
# yellow = "#E5C890"
#
# [schemes.frappe.hints.end]
# background = "#A5ADCE"
# foreground = "#303446"
#
# [schemes.frappe.hints.start]
# background = "#E5C890"
# foreground = "#303446"
#
# [schemes.frappe.normal]
# black = "#51576D"
# blue = "#8CAAEE"
# cyan = "#81C8BE"
# green = "#A6D189"
# magenta = "#F4B8E4"
# red = "#E78284"
# white = "#B5BFE2"
# yellow = "#E5C890"
#
# [schemes.frappe.primary]
# background = "#303446"
# bright_foreground = "#C6D0F5"
# dim_foreground = "#C6D0F5"
# foreground = "#C6D0F5"
#
# [schemes.frappe.search.focused_match]
# background = "#A6D189"
# foreground = "#303446"
#
# [schemes.frappe.search.footer_bar]
# background = "#A5ADCE"
# foreground = "#303446"
#
# [schemes.frappe.search.matches]
# background = "#A5ADCE"
# foreground = "#303446"
#
# [schemes.frappe.selection]
# background = "#F2D5CF"
# text = "#303446"
#
# [schemes.frappe.vi_mode_cursor]
# cursor = "#BABBF1"
# text = "#303446"
#
# [schemes.github_light.bright]
# black = "#969896"
# blue = "#e8e8e8"
# cyan = "#333333"
# green = "#f5f5f5"
# magenta = "#ffffff"
# red = "#0086b3"
# white = "#ffffff"
# yellow = "#c8c8fa"
#
# [schemes.github_light.cursor]
# cursor = "#9775FA"
# text = "#ffffff"
#
# [schemes.github_light.normal]
# black = "#ffffff"
# blue = "#795da3"
# cyan = "#183691"
# green = "#183691"
# magenta = "#a71d5d"
# red = "#ed6a43"
# white = "#333333"
# yellow = "#795da3"
#
# [schemes.github_light.primary]
# background = "#ffffff"
# foreground = "#333333"
#
# [[schemes.macchiato.indexed_colors]]
# color = "#F5A97F"
# index = 16
#
# [[schemes.macchiato.indexed_colors]]
# color = "#F4DBD6"
# index = 17
#
# [schemes.macchiato.bright]
# black = "#5B6078"
# blue = "#8AADF4"
# cyan = "#8BD5CA"
# green = "#A6DA95"
# magenta = "#F5BDE6"
# red = "#ED8796"
# white = "#A5ADCB"
# yellow = "#EED49F"
#
# [schemes.macchiato.cursor]
# cursor = "#F4DBD6"
# text = "#24273A"
#
# [schemes.macchiato.dim]
# black = "#494D64"
# blue = "#8AADF4"
# cyan = "#8BD5CA"
# green = "#A6DA95"
# magenta = "#F5BDE6"
# red = "#ED8796"
# white = "#B8C0E0"
# yellow = "#EED49F"
#
# [schemes.macchiato.hints.end]
# background = "#A5ADCB"
# foreground = "#24273A"
#
# [schemes.macchiato.hints.start]
# background = "#EED49F"
# foreground = "#24273A"
#
# [schemes.macchiato.normal]
# black = "#494D64"
# blue = "#8AADF4"
# cyan = "#8BD5CA"
# green = "#A6DA95"
# magenta = "#F5BDE6"
# red = "#ED8796"
# white = "#B8C0E0"
# yellow = "#EED49F"
#
# [schemes.macchiato.primary]
# background = "#24273A"
# bright_foreground = "#CAD3F5"
# dim_foreground = "#CAD3F5"
# foreground = "#CAD3F5"
#
# [schemes.macchiato.search.focused_match]
# background = "#A6DA95"
# foreground = "#24273A"
#
# [schemes.macchiato.search.footer_bar]
# background = "#A5ADCB"
# foreground = "#24273A"
#
# [schemes.macchiato.search.matches]
# background = "#A5ADCB"
# foreground = "#24273A"
#
# [schemes.macchiato.selection]
# background = "#F4DBD6"
# text = "#24273A"
#
# [schemes.macchiato.vi_mode_cursor]
# cursor = "#B7BDF8"
# text = "#24273A"
#
# [schemes.nightfly.bright]
# black = "#7c8f8f"
# blue = "#82aaff"
# cyan = "#7fdbca"
# green = "#21c7a8"
# magenta = "#ae81ff"
# red = "#ff5874"
# white = "#d6deeb"
# yellow = "#ecc48d"
#
# [schemes.nightfly.cursor]
# cursor = "#9ca1aa"
# text = "#080808"
#
# [schemes.nightfly.normal]
# black = "#1d3b53"
# blue = "#82aaff"
# cyan = "#7fdbca"
# green = "#a1cd5e"
# magenta = "#c792ea"
# red = "#fc514e"
# white = "#a1aab8"
# yellow = "#e3d18a"
#
# [schemes.nightfly.primary]
# background = "#011627"
# bright_foreground = "#eeeeee"
# foreground = "#bdc1c6"
#
# [schemes.nightfly.selection]
# background = "#b2ceee"
# text = "#080808"
#
# [schemes.nordfox.bright]
# black = "0x465780"
# blue = "0x8cafd2"
# cyan = "0x93ccdc"
# green = "0xb1d196"
# magenta = "0xc895bf"
# red = "0xd06f79"
# white = "0xe7ecf4"
# yellow = "0xf0d399"
#
# [schemes.nordfox.cursor]
# cursor = "0xcdcecf"
# text = "0x2e3440"
#
# [schemes.nordfox.normal]
# black = "0x3b4252"
# blue = "0x81a1c1"
# cyan = "0x88c0d0"
# green = "0xa3be8c"
# magenta = "0xb48ead"
# red = "0xbf616a"
# white = "0xe5e9f0"
# yellow = "0xebcb8b"
#
# [schemes.nordfox.primary]
# background = "0x2e3440"
# foreground = "0xcdcecf"
#
# [schemes.oxocarbon.bright]
# black = "#393939"
# blue = "#33b1ff"
# cyan = "#3ddbd9"
# green = "#42be65"
# magenta = "#ff7eb6"
# red = "#ee5396"
# white = "#ffffff"
# yellow = "#ffe97b"
#
# [schemes.oxocarbon.cursor]
# cursor = "#ffffff"
# text = "#161616"
#
# [schemes.oxocarbon.line_indicator]
# background = "None"
# foreground = "None"
#
# [schemes.oxocarbon.normal]
# black = "#262626"
# blue = "#33b1ff"
# cyan = "#3ddbd9"
# green = "#42be65"
# magenta = "#ff7eb6"
# red = "#ee5396"
# white = "#dde1e6"
# yellow = "#ffe97b"
#
# [schemes.oxocarbon.primary]
# background = "#161616"
# foreground = "#ffffff"
#
# [schemes.oxocarbon.selection]
# background = "0xdfdad9"
# text = "0x575279"
#
# [schemes.oxocarbon.vi_mode_cursor]
# cursor = "#ffffff"
# text = "#161616"
#
# [schemes.rasmus.bright]
# black = "#4c4c4b"
# blue = "#a6cded"
# cyan = "#94c9b2"
# green = "#7aae98"
# magenta = "#f7b4e1"
# red = "#ffafa5"
# white = "#eaeaea"
# yellow = "#ffdeaa"
#
# [schemes.rasmus.cursor]
# cursor = "#b6b6b5"
# text = "#1a1a19"
#
# [schemes.rasmus.normal]
# black = "#333332"
# blue = "#8db4d4"
# cyan = "#7bb099"
# green = "#61957f"
# magenta = "#de9bc8"
# red = "#ff968c"
# white = "#d1d1d1"
# yellow = "#ffc591"
#
# [schemes.rasmus.primary]
# background = "#1a1a19"
# foreground = "#d1d1d1"
#
# [schemes.rose-pine-dawn.bright]
# black = "0x9893a5"
# blue = "0x56949f"
# cyan = "0xd7827e"
# green = "0x286983"
# magenta = "0x907aa9"
# red = "0xb4637a"
# white = "0x575279"
# yellow = "0xea9d34"
#
# [schemes.rose-pine-dawn.cursor]
# cursor = "0x575279"
# text = "0xfaf4ed"
#
# [schemes.rose-pine-dawn.hints.end]
# background = "#fffaf3"
# foreground = "#9893a5"
#
# [schemes.rose-pine-dawn.hints.start]
# background = "#fffaf3"
# foreground = "#797593"
#
# [schemes.rose-pine-dawn.line_indicator]
# background = "None"
# foreground = "None"
#
# [schemes.rose-pine-dawn.normal]
# black = "0xf2e9e1"
# blue = "0x56949f"
# cyan = "0xd7827e"
# green = "0x286983"
# magenta = "0x907aa9"
# red = "0xb4637a"
# white = "0x575279"
# yellow = "0xea9d34"
#
# [schemes.rose-pine-dawn.primary]
# background = "0xfaf4ed"
# foreground = "0x575279"
#
# [schemes.rose-pine-dawn.selection]
# background = "0xdfdad9"
# text = "0x575279"
#
# [schemes.rose-pine-dawn.vi_mode_cursor]
# cursor = "0xcecacd"
# text = "0x575279"
#
# [schemes.rose-pine-moon.bright]
# black = "0x6e6a86"
# blue = "0x9ccfd8"
# cyan = "0xea9a97"
# green = "0x3e8fb0"
# magenta = "0xc4a7e7"
# red = "0xeb6f92"
# white = "0xe0def4"
# yellow = "0xf6c177"
#
# [schemes.rose-pine-moon.cursor]
# cursor = "0xe0def4"
# text = "0x232136"
#
# [schemes.rose-pine-moon.hints.end]
# background = "#2a273f"
# foreground = "#6e6a86"
#
# [schemes.rose-pine-moon.hints.start]
# background = "#2a273f"
# foreground = "#908caa"
#
# [schemes.rose-pine-moon.line_indicator]
# background = "None"
# foreground = "None"
#
# [schemes.rose-pine-moon.normal]
# black = "0x393552"
# blue = "0x9ccfd8"
# cyan = "0xea9a97"
# green = "0x3e8fb0"
# magenta = "0xc4a7e7"
# red = "0xeb6f92"
# white = "0xe0def4"
# yellow = "0xf6c177"
#
# [schemes.rose-pine-moon.primary]
# background = "0x232136"
# foreground = "0xe0def4"
#
# [schemes.rose-pine-moon.selection]
# background = "0x44415a"
# text = "0xe0def4"
#
# [schemes.rose-pine-moon.vi_mode_cursor]
# cursor = "0x56526e"
# text = "0xe0def4"
#
# [schemes.tokyo_night.bright]
# black = "0x444b6a"
# blue = "0x7da6ff"
# cyan = "0x0db9d7"
# green = "0xb9f27c"
# magenta = "0xbb9af7"
# red = "0xff7a93"
# white = "0xacb0d0"
# yellow = "0xff9e64"
#
# [schemes.tokyo_night.cursor]
# cursor = "#c0caf5"
# text = "#1a1b26"
#
# [schemes.tokyo_night.normal]
# black = "0x32344a"
# blue = "0x7aa2f7"
# cyan = "0x449dab"
# green = "0x9ece6a"
# magenta = "0xad8ee6"
# red = "0xf7768e"
# white = "0x787c99"
# yellow = "0xe0af68"
#
# [schemes.tokyo_night.primary]
# background = "0x1a1b26"
# foreground = "0xa9b1d6"
#
# [[schemes.tokyo_night_moon.indexed_colors]]
# color = "0xff966c"
# index = 16
#
# [[schemes.tokyo_night_moon.indexed_colors]]
# color = "0xc53b53"
# index = 17
#
# [schemes.tokyo_night_moon.bright]
# black = "0x444a73"
# blue = "0x82aaff"
# cyan = "0x86e1fc"
# green = "0xc3e88d"
# magenta = "0xc099ff"
# red = "0xff757f"
# white = "0xc8d3f5"
# yellow = "0xffc777"
#
# [schemes.tokyo_night_moon.cursor]
# cursor = "#C8D3F5"
# text = "0x222436"
#
# [schemes.tokyo_night_moon.normal]
# black = "0x1b1d2b"
# blue = "0x82aaff"
# cyan = "0x86e1fc"
# green = "0xc3e88d"
# magenta = "0xc099ff"
# red = "0xff757f"
# white = "0x828bb8"
# yellow = "0xffc777"
#
# [schemes.tokyo_night_moon.primary]
# background = "0x222436"
# foreground = "0xc8d3f5"
#
# [schemes.tokyo_night_storm.bright]
# black = "0x444b6a"
# blue = "0x7da6ff"
# cyan = "0x0db9d7"
# green = "0xb9f27c"
# magenta = "0xbb9af7"
# red = "0xff7a93"
# white = "0xacb0d0"
# yellow = "0xff9e64"
#
# [schemes.tokyo_night_storm.cursor]
# cursor = "#c0caf5"
# text = "#1a1b26"
#
# [schemes.tokyo_night_storm.normal]
# black = "0x32344a"
# blue = "0x7aa2f7"
# cyan = "0x449dab"
# green = "0x9ece6a"
# magenta = "0xad8ee6"
# red = "0xf7768e"
# white = "0x787c99"
# yellow = "0xe0af68"
#
# [schemes.tokyo_night_storm.primary]
# background = "0x24283b"
# foreground = "0xa9b1d6"
#
# [schemes.zenbones_dark.bright]
# black = "#403833"
# blue = "#61ABDA"
# cyan = "#65B8C1"
# green = "#8BAE68"
# magenta = "#CF86C1"
# red = "#E8838F"
# white = "#888F94"
# yellow = "#D68C67"
#
# [schemes.zenbones_dark.cursor]
# cursor = "#FFD866"
# text = "#1C1917"
#
# [schemes.zenbones_dark.normal]
# black = "#1C1917"
# blue = "#6099C0"
# cyan = "#66A5AD"
# green = "#819B69"
# magenta = "#B279A7"
# red = "#DE6E7C"
# white = "#B4BDC3"
# yellow = "#B77E64"
#
# [schemes.zenbones_dark.primary]
# background = "#171210"
# foreground = "#B4BDC3"
#
# [schemes.zenbones_light.bright]
# black = "#CFC1BA"
# blue = "#1D5573"
# cyan = "#2B747C"
# green = "#3F5A22"
# magenta = "#7B3B70"
# red = "#94253E"
# white = "#4F5E68"
# yellow = "#803D1C"
#
# [schemes.zenbones_light.cursor]
# cursor = "#9775FA"
# text = "#F0EDEC"
#
# [schemes.zenbones_light.normal]
# black = "#F0EDEC"
# blue = "#286486"
# cyan = "#3B8992"
# green = "#4F6C31"
# magenta = "#88507D"
# red = "#A8334C"
# white = "#2C363C"
# yellow = "#944927"
#
# [schemes.zenbones_light.primary]
# background = "#F8F6F5"
# foreground = "#2C363C"
