#!/usr/bin/env sh

theme="$1"
color_scheme="$HOME/.config/alacritty/zenbones_scheme.yml"

# check file exists
if [ ! -f "$color_scheme" ]; then
    echo "Color scheme file not found!"
    exit 0
fi

sed -i '' -e "s#^colors: \*.*#colors: *$theme#g" $color_scheme
